### PR TITLE
Drop support for Python 3.7 (anndata 0.9.0 dropped support)

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

---

anndata 0.9.0 dropped support for Python 3.7 https://github.com/scverse/anndata/pull/820

```sh
mamba create --yes -n test-anndata anndata
mamba activate test-anndata
python --version
## Python 3.11.3
python -c 'import anndata; print(anndata.__version__)'
## 0.9.0
mamba install python=3.7
python --version
## Python 3.7.12
python -c 'import anndata; print(anndata.__version__)'
## Traceback (most recent call last):
##   File "~/mambaforge/envs/test-anndata/lib/python3.7/site-packages/anndata/_metadata.py", line 25, in <module>
##     from setuptools_scm import get_version
## ModuleNotFoundError: No module named 'setuptools_scm'
## 
## During handling of the above exception, another exception occurred:
## 
## Traceback (most recent call last):
##   File "<string>", line 1, in <module>
##   File "~/mambaforge/envs/test-anndata/lib/python3.7/site-packages/anndata/__init__.py", line 3, in <module>
##     from ._metadata import __version__, within_flit
##   File "~/mambaforge/envs/test-anndata/lib/python3.7/site-packages/anndata/_metadata.py", line 30, in <module>
##     from importlib.metadata import metadata
## ModuleNotFoundError: No module named 'importlib.metadata'
```

The version 0.9.0 binary uploaded after merging #27 will still be installed in Python 3.7 environments, and will break them. If we think this will affect many users, I think we could submit a repodata patch to fix it

### CODE REVIEW

**Comment by jdblischak** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
Also, I noticed you were manually bundling the license file. This isn't necessary since `LICENSE` is included in the release tarball uploaded to PyPI:

```sh
wget https://files.pythonhosted.org/packages/8d/c6/7a9eead099257402c53aa67130d41b28be870bfd40c221fbeb40a923009f/anndata-0.9.0.tar.gz
tar --list -f anndata-0.9.0.tar.gz | grep LICENSE
## anndata-0.9.0/LICENSE
```

This is guaranted because of the following [line](https://github.com/scverse/anndata/blame/main/pyproject.toml#L12) in `pyproject.toml`, added in commit [44d0aba](https://github.com/scverse/anndata/commit/44d0abad1fd82b3fc85f8158bfb7b8355b26f632)

```toml
license = {file = "LICENSE"}
```

**Comment by flying-sheep** [comment]
great, thank you!

**Comment by jdblischak** [comment]
I submitted a repodata patch to fix build 0

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/433

**Comment by jdblischak** [comment]
My repodata patch PR (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/433) was merged, so build 0 is also fixed now (ie it now requires Python >=3.8)

**Pull request merged**
