### PR TITLE
Follow up of #21: convert to noarch

### PR DESCRIPTION
**Pull request by HeavyTony2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Comment by HeavyTony2** [comment]
@flying-sheep
To answer to that question:
https://github.com/conda-forge/anndata-feedstock/pull/21#discussion_r834262637

Normally, we're not suppose to put selectors to package with noarch. So, it triggers a lintin-error as you can notice.
What are the options then?
1. Keeping the dependancies for all python versions to keep the noarch. ` typing_extensions` has no other dependancies than `python` and `pip`. `importlib_metadata` requires` typing_extension` and `zipp`, which doesn't require another dependencies than `python` and `pip`. In other words, keeping them in the recipe wouldn't make a notable difference for users with Python 3.8 and plus.  ALSO: Noarch tarball would be 76kb. 76kb+3.8kb for` importlib_metadata` tarball + 27kb for ` typing_extensions ` is stil less than the current 150kb.
2. Keeping it separated instead of noarch to manage that specificity. However, this is already a noarch package on Pypi. It's then more convenient to install it from Pypi than Conda-Forge.
3. Keeping the selectors for the two packages and keeping the noarch. However, it would trigger a linting error for earch update until Python 3.7 stops being supported by Conda-Forge.

**Comment by flying-sheep** [comment]
What is the linting rule about? Will the selectors be ignored? If so, they should be removed. If they are functional, I don’t understand what the linting rule is about, as keeping the selector would be semantically ideal.

**Comment by ivirshup** [comment]
I think we'll drop python 3.7 with the next release cycle.

Does that simplify things a bit here?

**Comment by HeavyTony2** [comment]
@ivirshup So, in that case, it would be
```
requirements:
  host:
    - python >=3.8
    - pip
    - flit-core
    - setuptools_scm
    - pytoml
  run:
    - python >=3.8 
    - pandas >=0.23.0
    - scipy >=1.4
    - h5py
    - numpy >=1.16.5
    - natsort
    - packaging >=20
```

**Comment by HeavyTony2** [comment]
@flying-sheep I found out the problem: If I build the package on python 3.7, our two deps will be listed in the run list. However, they won't if the package is built on a higher version. The conda-forge noarch packages are currently built on Python 3.10 . It means Python 3.7 users won't have the deps installed because they won't be listed in the recipe.
So the choice is between having the package only avalaible for 3.8+ or having this two deps for all.

**Comment by HeavyTony2** [comment]
ping @conda-forge/anndata

**Comment by ivirshup** [comment]
@HeavyTony2 I think you'd need to bump that h5py dependency to `- h5py >=3.0`  as well.

But I wouldn't want to drop 3.7 for the conda build until anndata drops support for 3.7.

**Comment by HeavyTony2** [comment]
> @HeavyTony2 I think you'd need to bump that h5py dependency to `- h5py >=3.0` as well.
> 
> But I wouldn't want to drop 3.7 for the conda build until anndata drops support for 3.7.

@ivirshup Updated for h5py. I even left a note about the two 3.7 specific dependancies.

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Comment by HeavyTony2** [comment]
ping @conda-forge/anndata

**Comment by HeavyTony2** [comment]
@conda-forge-admin, please rerender

**Comment by HeavyTony2** [comment]
ping @conda-forge/anndata

**Pull request merged**
