### PR TITLE
anndata 0.11.0 requires python >= 3.10

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

The 0.11.0 update PR was automerged before its dependencies could be updated (#42). It now requires a minimum of python 3.10 (https://github.com/scverse/anndata/pull/1712). Because the conda recipe was not updated, anndata 0.11.0 will be installed into conda envs with python 3.9, breaking them.

I implemented the new `python_min` strategy for noarch python recipes like this. It should help catch these types of problems automatically in the future.

https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python
https://github.com/conda-forge/cfep/blob/main/cfep-25.md

### CODE REVIEW

**Comment by jdblischak** [comment]
@conda-forge/anndata ready for review

**Review by flying-sheep — APPROVED** [review]
looks good. is there some automation to fix up deps using e.g. https://github.com/regro/cf-graph-countyfair?

**Comment by jdblischak** [comment]
> is there some automation to fix up deps using e.g. https://github.com/regro/cf-graph-countyfair?

Unfortunately not. The [autotick bot](https://github.com/regro/cf-scripts) uses the conda-forge dependency graph created by cf-graph-countyfair to provide hints about dependencies that have been recently updated in conda-forge. But ultimately it is conda-forge metadata, not the actual package data from PyPI, so it is unaware of new updates.

Unfortunately the flexibility of Python packaging makes it difficult to obtain a simple list of requirements ([Why PyPI Doesn't Know Your Projects Dependencies](https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/)). Trying to update the dependencies would require generating a recipe (eg via [grayskull](https://github.com/conda/grayskull)), and then trying to merge the new requirements with the existing ones.

**Comment by flying-sheep** [comment]
> Unfortunately the flexibility of Python packaging makes it difficult to obtain a simple list of requirements ([Why PyPI Doesn't Know Your Projects Dependencies](https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/)).

I’m sorry but absolutely not. That blog post is outdated, I don’t think it should be referenced still. Its last paragraph wistfully wishes for a time when PEP 517 fixes the situation. And the time has come some years ago. Here’s e.g. how I ask PyPI for dependencies of a package: https://github.com/flying-sheep/PKGBUILDs/blob/492ebf62099a919bdd247259e97ec3119f832157/src/nvcheck/update/sources/pypi.py#L56-L84

As you can see in the commented out section, an even simpler API existed on PyPI for a long time.

And almost all packages I care about specify their dependencies declaratively in pyproject.toml. E.g. GitHub can and does read their dependencies from there, so even if the above wasn‘t true, we could reliably get this information for many many packages.

Don‘t get me wrong, this is a 80-20 situation: It’d work perfectly for all PyPI packages that reliably upload wheels. Which we definitely do and anyone else following best practices does that as well.

> Trying to update the dependencies would require generating a recipe (eg via [grayskull](https://github.com/conda/grayskull)), and then trying to merge the new requirements with the existing ones.

Or more directly using APIs for that. Some work, but by no means hard for most well-maintained packages that are both on conda-forge and pypi. And it wouldn’t have to work for the rest.

**Comment by jdblischak** [comment]
> I’m sorry but absolutely not. That blog post is outdated

@flying-sheep thanks for updating me! My knowledge of PyPI is clearly outdated. Looks like PEPs like [517](https://peps.python.org/pep-0517/) and [658](https://peps.python.org/pep-0658/) have greatly improved the situation.

> Or more directly using APIs for that. Some work, but by no means hard for most well-maintained packages that are both on conda-forge and pypi. And it wouldn’t have to work for the rest.

Automatically updating the requirements for the update PRs has been discussed for years. If you have ideas to share and/or spare cycles to contribute, the conda-forge community could greatly benefit from your expertise.

A good starting point is this Issue, https://github.com/regro/cf-scripts/issues/22, that started discussing automated dependency bumps back in 2018, and still gets the occasional comment. I also found the discussion in https://github.com/regro/cf-scripts/issues/1471 interesting because it notes the inherent tension between the requirements specified in the PyPI metadata versus what is required for maintaining the conda-forge ecosystem as a whole.

**Comment by flying-sheep** [comment]
Yeah, there is some serious lack of cross-pollination between the PyPI and conda ecosystems.

I’ll comment in the open issue, thanks

**Pull request merged**
